[정렬, 맵, 셋] 2116020 전유진
Altu-Bitu-Official/Altu-Bitu-4 pull request #11
Opened 2023-02-20 19:06 UTC by YujinJeon888888

### 인적사항
학번:   2116020
이름:     전유진
</br>

--- 
### 과제 제출
기존 제출 :   1431, 14425, 19636
추가 제출 :   

</br>
정렬 문제(1431)이랑, 맵셋문제(14425)를 문제의 의도에 맞지 않게 푼 것 같습니다. 
정렬문제는 sort 함수로 변형해서 풀 수 있을 것 같은데 능숙하지 않아서 버블정렬로 했고, 맵셋문제는 일단 맵을 썼긴 했는데 
이상하게 썼습니다. 
어떤식으로 푸는게 더 sort와 맵셋을 활용할 수 있을지 알려주실 수 있나요 ? 수업시간에 다루기로 이미
예정된 것이라면 수업에서 배우겠습니다.
감사합니다~

2023-02-23 15:04 UTC, jk0527 requested changes
**[정렬, 맵, 셋 알고리즘 코드 리뷰 완료]**

1431(P1), 14425(P3)

유진님 안녕하세요!
첫 과제인데도 정말 깔끔하게 풀어주셨네요!🥰🥰
저희가 준비한 샘플 코드와 정말 비슷해요! 정말 좋습니다:)
코드에 대한 주석이 세세하게 달려있어서 코드 리뷰하기 너무 좋았습니다!😎
몇 가지 코멘트 드렸습니다. 😊
P1인 문제는 꼭 수정해주시면 좋을 것 같아요. 그리고 변수명은 꼭 영어로 바꿔주세요!
궁금한 점이 있으면 리뷰어를 호출해주세요!

2023-02-23 15:04 UTC, jk0527 commented on 01_정렬, 맵, 셋/필수/1431.cpp
> +				arr[j + 1] = temp;
swap 함수를 쓰셔도 됩니다!

2023-02-23 15:04 UTC, jk0527 commented on 01_정렬, 맵, 셋/필수/1431.cpp
> +					}
똑같은 연산을 반복하고 있네요..! 함수화해도 좋을 것 같아요!

2023-02-23 15:04 UTC, jk0527 commented on 01_정렬, 맵, 셋/필수/1431.cpp
> +	//1. 연산
우와 연산 헷갈릴 수 있는데 정말 잘 구현하셨네요!! 이것도 좋은 연습이 되었을 것 같아요!😎😎
질문 주신 것처럼 사실 저희 의도는 sort함수와 비교 함수를 사용해서 푸는 것입니다.
강의에서 했던 것처럼 주어진 1~3조건을 비교 함수에 구현하면 돼요.
지금 구현하신 부분 중 일부를 그대로 비교 함수 안으로 옮기면 간단하게 풀 수 있어요!
라이브 코딩 [국영수 문제](https://github.com/Altu-Bitu-Official/Altu-Bitu-4/blob/main/01_%EC%A0%95%EB%A0%AC%2C%20%EB%A7%B5%2C%20%EC%85%8B/%EB%9D%BC%EC%9D%B4%EB%B8%8C%20%EC%BD%94%EB%94%A9/10825.cpp)를 복습하면서 풀어보시면 금방 풀릴 거예요!
한번 시도해 보시고 나중에 [샘플 코드](https://github.com/Altu-Bitu-Official/Altu-Bitu-4/blob/main/01_%EC%A0%95%EB%A0%AC%2C%20%EB%A7%B5%2C%20%EC%85%8B/%ED%95%84%EC%88%98/1431.cpp)도 참고해주세요🥰

2023-02-23 15:04 UTC, jk0527 commented on 01_정렬, 맵, 셋/필수/14425.cpp
> +	map<string, int> 집합_s;
변수 이름은 영어로 하는 것이 좋을 것 같아요. 알튜비튜에서 변수는 스네이크 표기법을 따르고 있기 때문에 set_s정도를 사용하면 좋을 것 같네요~!

2023-02-23 15:04 UTC, jk0527 commented on 01_정렬, 맵, 셋/필수/14425.cpp
> +	for (int i = 0; i < n1; i++) {
n1과 n2는  다시 사용하지 않으니 while 문으로 구현해도 될 것 같아요!

2023-02-23 15:04 UTC, jk0527 commented on 01_정렬, 맵, 셋/필수/14425.cpp
> +		if (집합_s[s] == 1) {
map을 이용해서 풀어주셨네요!! 좋은 방법 같아요. 이렇게 푸셔도 전혀 문제 없습니다!😎😎
근데 문제에 '집합'이라는 말이 나오네요..! set을 이용해도 간단하게 풀립니다!

2023-02-23 17:35 UTC, grdnr13 reviewed
**[정렬, 맵, 셋 구현 코드 리뷰 완료]**
19636(P2)
유진님, 안녕하세요!
몇 가지 코멘트 드렸으니, 확인해주시고 궁금한 점이 있으면 리뷰어를 호출해주세요!

과제 하시느라 수고하셨습니다 🥰🥰

2023-02-23 17:35 UTC, grdnr13 commented on 01_정렬, 맵, 셋/필수/19636.cpp
> +	int 일일_기초_대사량 = 다이어트_전_일일_에너지_섭취량_및_일일_기초_대사량;
컴파일 환경에 따라서 인코딩 등이 달라지면 한국어가 깨질 수도 있어서, 변수명은 영어로 하는 게 좋아요 😃

2023-02-23 17:35 UTC, grdnr13 commented on 01_정렬, 맵, 셋/필수/19636.cpp
> +	}
일일 기초 대사량 변화를 고려하지 않는 경우는 반복문을 돌리지 않고도 바로 연산으로도 구할 수 있어요
체중이 증가하는 경우는 주어지지 않으니, 사망 여부도 중간에 체크할 필요 없이 최종 체중만으로 체크가 가능하겠죠?

2023-02-23 17:35 UTC, grdnr13 commented on 01_정렬, 맵, 셋/필수/19636.cpp
> +		}
여기서 바로 "Danger Diet"조건이 만족되네요! 뒷 부분은 실행할 필요 없이 함수를 종료해도 되겠어요

2023-02-23 17:35 UTC, grdnr13 commented on 01_정렬, 맵, 셋/필수/19636.cpp
> +	else	cout << 다이어트_후_예상_체중 << " " << 일일_기초_대사량 << " " << yoyo << endl;
요요 체크하는 부분을 출력문 안에 넣으면 `yoyo` 변수를 선언하지 않아도 될 것 같네요!

2023-02-27 14:26 UTC, jk0527 reviewed
**[정렬, 맵, 셋 코드 수정 확인 완료]**

1431(P2), 14425(P3)

수정해주신 부분 모두 확인했습니다~! 😎
1431의 경우 논리적으로 틀린 곳이 없어서 P2를 드렸지만 꼭 수정해보셨으면 해요.
sort 함수와 비교 함수 사용 방법을 익히는 것이 나중을 위해서라도 정말 중요해서요..!
수정하시게 되면 리뷰어를 호출해주세요. 내일 일괄 머지를 할 거라 그 이후에 수정하시게 되면 슬랙 DM 주세요! 고생하셨습니다!! 🥰🥰

2023-02-27 14:26 UTC, jk0527 commented on 01_정렬, 맵, 셋/필수/1431.cpp
> +				}
같은 것이 반복되고 있네요. 함수화하면 좋을 것 같아요!

2023-02-27 14:26 UTC, jk0527 commented on 01_정렬, 맵, 셋/필수/1431.cpp
> +void compSum(vector<string> arr, int index_A, int index_B) {
이렇게 구현하셔도 되는데 아직도 조금 복잡해보여요. 직접 swap하지 말고 비교함수를 이용해 보는 것은 어떨까요? sort 함수와 비교 함수를 잘 활용하면 더 쉽게 풀 수 있어요! 샘플 코드를 꼭 참고해주세요!

2023-02-27 14:26 UTC, jk0527 commented on 01_정렬, 맵, 셋/필수/14425.cpp
> +//어떻게 풀어야 문제의 의도에 맞게 풀 수 있나요?
문제의 의도에 맞게 푸셨어요!

2023-02-27 14:26 UTC, jk0527 commented on 01_정렬, 맵, 셋/필수/14425.cpp
> +		if (set_s[s] == 1) {
`if (set_s[s])` 이렇게 하셔도 돼요!

2023-02-28 13:04 UTC, jk0527 approved these changes

2023-02-28 13:04 UTC, merged

2023-03-01 15:06 UTC, YujinJeon888888 commented on 01_정렬, 맵, 셋/필수/1431.cpp
> +void compSum(vector<string> arr, int index_A, int index_B) {
안녕하세요, 넵 그러겠습니다
시간이 안 나는 상황이라, 여유로울 때 수정해서 푸시해도 될까요? 다음주쯤이면 확실히 여유로워질 것 같습니다. 
혹시 기한이 따로 있는건가요? 그렇다면 마감기한 안에 수정하겠습니다.

2023-03-02 01:22 UTC, jk0527 commented on 01_정렬, 맵, 셋/필수/1431.cpp
> +void compSum(vector<string> arr, int index_A, int index_B) {
마감 기간은 없습니다~! 시간 날 때 천천히 수정해주셔도 됩니다!!🥰🥰