[우선순위 큐] 2176155 박지현
Altu-Bitu-Official/Altu-Bitu-4 pull request #157
Opened 2023-03-20 16:32 UTC by sawoll

### 인적사항
학번:   2176155
이름:     박지현
</br>

--- 
### 과제 제출
기존 제출 :   14235, 2075, 2607
추가 제출 :   

</br>

2023-03-21 07:35 UTC, dbswn reviewed
안녕하세요 채원님 !! 😊 코드도 깔끔해서 리뷰 드리기 너무 좋았습니다👍 간단한 코멘트 달았으니, 확인 부탁 드립니다!

p1은 반드시 수정해주셨으면 하는 부분이고, p2,p3는 참고만 해주셔도 괜찮습니다! 코드 수정하시면 리뷰어 호출 부탁드립니다! 수고하셨습니다🥰

2023-03-21 07:35 UTC, dbswn commented on 05_우선순위 큐/필수/14235.cpp
> +        if (a == 0) {
P3

c계열에서는 정수형이 0이면 false, 0이 아니라면 true로 자동으로 인식됩니다!
따라서 a가 0일 때 true를 반환하고 싶다면 !a라고 적을 수 있습니다

2023-03-21 07:35 UTC, dbswn commented on 05_우선순위 큐/필수/14235.cpp
> +                cout << -1 << '\n'; continue;
엔터가 빠진 것 같아요! (너무 사소하지만 일단 달아봤습니다 😄 )

2023-03-21 07:35 UTC, dbswn commented on 05_우선순위 큐/필수/2075.cpp
> +    cout << pq.top();
정말 완벽합니다 👍

2023-03-23 04:48 UTC, grdnr13 requested changes
**[우선순위 큐 구현 코드 리뷰 완료]**
2607(P1)
지현님, 안녕하세요! 올바르게 동작하지 않는 코드를 제출해주셨네요😥😥
백준 예시로 공개되지 않은 테스트케이스에서 제대로 작동하지 않는 코드는 틀렸다고 채점됩니다! 알튜비튜의 출석 기준은 백준 채점결과니, 틀렸다고 뜨면 꼭 슬랙 질문 채널에서 제출 전 질문해주세요~!
제출기한이 지나고 질문하셔도 됩니다!! 질문 채널은 언제나 열려있어요
틀린 코드를 제출하시면 전반적인 코드리뷰가 지연될 수밖에 없어 양해 부탁드립니다

제출해주신 코드에 대해 반례 제공해드리니, 수정 후 저(@grdnr13)를 호출해주세요
추가제출 기한 내에 고쳐주신다면 과제제출로 인정해드리겠습니다!

반례1
```text
2
ABAAC
ABAB
```
반례 2
```text
8
DOG
GOD
GOOD
DOGL
GD
PGG
G
DOGOD
```

2023-03-24 10:41 UTC, sawoll commented
@grdnr13 안녕하세요 튜터님 죄송합니다 수정한다는 것을 깜빡한 것 같습니다...수정해 새로 커밋했습니다. 벡터 이름을 혼동한 오류였습니다. 기간이 늦어 아마 과제제출로 인정이 되지 않을 것 같지만 늦게나마 수정합니다. 죄송합니다...

2023-03-24 11:12 UTC, grdnr13 commented
> 

안녕하세요
이번까지는 과제 제출 인정해드리겠습니다!!
다음부터는 질문 채널에 꼭 질문해주세요~
튜터들이 단기간에 리뷰해야 하는 코드가 많다보니, 틀린 코드를 풀리퀘에 바로 제출하시면 리뷰가 밀려서 양해 부탁드려요🙇

2023-03-24 13:40 UTC, sawoll commented
네 알겠습니다. 감사합니다...!!

2023-04-04 13:12 UTC, closed without merging