[우선순위큐] 1976435 황채원
Altu-Bitu-Official/Altu-Bitu-4 pull request #163
Opened 2023-03-21 04:32 UTC by uommou

### 인적사항
학번:   1976435
이름:    황채원
</br>

--- 
### 과제 제출
기존 제출 :   2607, 2075, 14235
추가 제출 :   

2067번 예제는 결과가 똑같이 나오는데 백준에서는 틀렸다고 나옵니다! 어디가 틀렸는지 알 수 있을까요?
</br>

2023-03-21 07:54 UTC, dbswn reviewed
안녕하세요 채원님 !! 😊 코드도 깔끔하고 주석도 잘 적혀 있어 리뷰 드리기 너무 좋았습니다👍 간단한 코멘트 달았으니, 확인 부탁 드립니다!

p1은 반드시 수정해주셨으면 하는 부분이고, p2,p3는 참고만 해주셔도 괜찮습니다! 코드 수정하시면 리뷰어 호출 부탁드립니다! 수고하셨습니다🥰

2023-03-21 07:54 UTC, dbswn commented on 05_우선순위 큐/필수/14235.cpp
> +		if (a == 0) { // 아이들을 만남
P3

c계열에서는 정수형이 0이면 false, 0이 아니라면 true로 자동으로 인식됩니다!
따라서 a가 0일 때 true를 반환하고 싶다면 !a라고 적을 수 있습니다

2023-03-21 07:54 UTC, dbswn commented on 05_우선순위 큐/필수/2075.cpp
> +		cin >> num;
입력과 출력을 함수에서 관리하게 될 경우, 함수의 용도가 굉장히 불명확해져요. 특히 함수화를 하는 이유는 특정 코드를 계속 반복해서 쓸 수 있도록 (재사용성을 높임) 하기 위함인데, 입력과 출력을 같이 해버리면 해당 함수를 다른 곳에서  또 쓰기도 애매해지죠! 따라서 입력과 출력은 메인에서만 하도록 권장드리고 있습니다!! ✨✨

2023-03-21 07:54 UTC, dbswn commented on 05_우선순위 큐/필수/2075.cpp
> +		}
완벽합니다!! 👍

2023-03-23 04:58 UTC, grdnr13 requested changes
**[우선순위 큐 구현 코드 리뷰 완료]**
2607(P1)
채원님, 안녕하세요!
이번 구현문제 코드pr로 틀린 코드를 제출해주신 분들이 너무 많아, 전반적인 코드리뷰가 지연되어 질문답변이 어려워진 점 양해부탁드립니다🙇‍♀️🙇‍♀️
제출해주신 코드에 대해 반례 제공해드리니, 수정 후 저(@grdnr13)를 호출해주세요

추가제출 기한 내에 고쳐주신다면 과제제출로 인정해드리겠습니다!

반례1
```text
2
AABCCD
ABBCDD
```
반례2
```text
2
ABAAC
ABAB
```

2023-03-23 14:52 UTC, uommou commented
> 

답안 코드에 주석 달아서 추가제출 완료했습니다!

2023-03-24 07:59 UTC, grdnr13 commented
> 

확인 완료했습니다!! 이번 과제도 수고하셨습니다😀

2023-04-01 03:02 UTC, merged