[그리디 알고리즘] 1971066 김채연
Altu-Bitu-Official/Altu-Bitu-4 pull request #197
Opened 2023-03-28 06:29 UTC by chaeyeonS2

### 인적사항
학번:   1971066
이름:    김채연
</br>

--- 
### 과제 제출
기존 제출 :   1213, 17451
추가 제출 :   

</br>

질문 : 1213 코드 아래에 주석으로 달아두었습니다! 요약하자면 map 대신 <pair>을 사용했을 때 코드는 왜 동작하지 않았는가 입니다. 항상 감사합니다!

2023-03-29 14:26 UTC, sujeong000 submitted a review, later dismissed
추가 제출의 경우, 샘플 답안의 **모든 줄**에 주석을 남겨주셔야 합니다!

2023-03-29 14:48 UTC, sujeong000 requested changes
추가 제출의 경우 샘플 답안의 **모든 줄**에 주석을 작성해주셔야 합니다!

2023-03-29 15:07 UTC, grdnr13 approved these changes
**[그리디 알고리즘 코드 리뷰 완료]**
1213(P3), 17451(P3)
채연님, 안녕하세요!
알고리즘 문제 잘 풀어주셨네요! 😊😊
몇 가지 간단한 코멘트 드렸으니, 확인해주시고 궁금한 점이 있으면 리뷰어를 호출해주세요!

알고리즘 문제는 여기서 마무리하셔도 될 것 같아요! 이번 과제도 수고하셨습니다🥰

2023-03-29 15:07 UTC, grdnr13 commented on 06_그리디 알고리즘/필수/1213.cpp
> +}
바깥의 반복문 `char i`와 내부의 반복문 `int i`가 변수명이 겹쳐 충돌을 일으킨 것 같네요😊
`i`라는 변수명은 한 번 쓰이고 마는 간단한 반복문에서 쓰는 게 제일 이상적이에요

2023-03-29 15:07 UTC, grdnr13 commented on 06_그리디 알고리즘/필수/1213.cpp
> +    map<char, int> m = setMap(name);
p3. map 대신에 배열을 이용하면 코드가 더 간단해질 것 같네요😁

2023-03-29 15:07 UTC, grdnr13 commented on 06_그리디 알고리즘/필수/1213.cpp
> +    char c = '0';   //홀수일 경우 알파벳을 저장할 변수
p3. 변수명은 변수의 쓰임이나 특징에 관련된 이름으로 정하는게 좋아요

2023-03-29 15:07 UTC, grdnr13 commented on 06_그리디 알고리즘/필수/1213.cpp
> +map<char, int> setMap(string &name){
함수화 좋아요👍👍

2023-03-29 15:07 UTC, grdnr13 commented on 06_그리디 알고리즘/필수/1213.cpp
> +    }
p3. 팰린드롬 뒷부분 출력은 두 가지 경우에서 유사하니, 하나로 합칠 수 있을 것 같네요

2023-03-29 15:07 UTC, grdnr13 commented on 06_그리디 알고리즘/필수/17451.cpp
> +            ans = v[i]*tmp;
p3. `tmp`는 연산에서 한 번만 쓰이니, 코드를 한 줄로 줄일 수 있을 것 같아요

2023-03-30 01:48 UTC, chaeyeonS2 commented
> 추가 제출의 경우 샘플 답안의 **모든 줄**에 주석을 작성해주셔야 합니다!

앗 수정했습니다!!

2023-03-30 01:49 UTC, sujeong000 approved these changes
**[그리디 구현 코드 추가 제출 확인 완료]**

2023-04-04 13:45 UTC, merged