[투포인터] 2176155 박지현
Altu-Bitu-Official/Altu-Bitu-4 pull request #314
Opened 2023-05-16 08:22 UTC by sawoll

### 인적사항
학번: 2176155  
이름: 박지현    
</br>

--- 
### 과제 제출
기존 제출 :20437, 20922   
추가 제출 :   

</br>
나머지는 추가 제출하겠습니다.

2023-05-19 07:36 UTC, kwakrhkr59 requested changes
**[투포인터 필수 알고리즘 코드리뷰 완료]**
- 20437: P1

안녕하세요 지현님~ 투포인터 필수 알고리즘 문제 코드 리뷰 완료되셨습니다! 슬라이딩 윈도우와 투포인터를 사용해 문제를 잘 해결해주셨네요👍👍 다만 20437번 문제에서 한 부분 때문에 백준 통과가 되고 있지 않는 것으로 보입니다😥 과제 제출 인정 기준은 백준 통과 여부이므로 확인해보시고 수정해주시길 바라겠습니다...! 질문 있으시면 언제든 리뷰어로 호출해주세요:) 수고 많으셨습니다~

2023-05-19 07:36 UTC, kwakrhkr59 commented on 11_투 포인터/필수/BOJ_20437.cpp
> +                int tmp2=alpha[j][end]-alpha[j][start]+1;
슬라이딩 윈도우를 활용해 길이를 잘 구해주셨네요😍😍

2023-05-19 07:36 UTC, kwakrhkr59 commented on 11_투 포인터/필수/BOJ_20437.cpp
> +                ans2=max(tmp2, ans2);
tmp1, tmp2와 ans1, ans2를 따로 구분하지 않고 바로 ans1, ans2로 min(), max() 적용해주셔도 괜찮을 듯 하네요!

2023-05-19 07:36 UTC, kwakrhkr59 commented on 11_투 포인터/필수/BOJ_20437.cpp
> +vector<int> alpha[26];
P1. 지금 이 부분 때문에 백준 통과가 되지 않고 있는 것 같습니다...! 이 문제는 여러 개의 코너케이스를 다뤄야 하기 때문에 같은 벡터에 alpha를 지속적으로 추가해주신다면 앞의 케이스가 뒤의 케이스에 영향을 미치게 되겠죠! 이 부분 수정해보시면 될 것 같습니다😁

2023-05-19 07:36 UTC, kwakrhkr59 commented on 11_투 포인터/필수/BOJ_20437.cpp
> +        for(int j=0;j<26;j++){
P3. main은 최대한 간단하게 해주세요! main에서는 최대한 입출력만 담당하도록 하고, 반복해서 사용되는 로직의 경우 함수화 해주신다면 보다 더 깔끔한 코드를 만들 수 있을 것 같습니다😊

2023-05-19 07:36 UTC, kwakrhkr59 commented on 11_투 포인터/필수/BOJ_20437.cpp
> +vector<int> alpha[26];
26은 알파벳의 개수를 가리키는 숫자이죠! 이런 식으로 특정한 의미를 가지고 있는 숫자는 상수화해주시면 숫자의 의미를 보다 더 명확하게 전달할 수 있을 것 같네요😄

2023-05-19 07:36 UTC, kwakrhkr59 commented on 11_투 포인터/필수/BOJ_20922.cpp
> +    }
투포인터 활용 너무 좋습니다👍👍

2023-05-19 10:02 UTC, sawoll commented on 11_투 포인터/필수/BOJ_20437.cpp
> +vector<int> alpha[26];
헉 방금 확인했습니다...!ㅠㅠ 최대한 빨리 수정해 재 제출하겠습니다!

2023-05-19 10:07 UTC, sawoll commented on 11_투 포인터/필수/BOJ_20437.cpp
> +vector<int> alpha[26];
수정 완료해 새롭게 커밋했습니다! 확인 부탁드립니다.

2023-05-20 10:57 UTC, kwakrhkr59 commented on 11_투 포인터/필수/BOJ_20437.cpp
> +vector<int> alpha[26];
넵 확인했습니다! 수고 많으셨습니다😊

2023-05-24 03:54 UTC, merged