[정렬, 맵, 셋] 2076414 최수현
Altu-Bitu-Official/Altu-Bitu-4 pull request #4
Opened 2023-02-20 09:59 UTC by suhhyun524

### 인적사항
학번:   2076414
이름:   최수현
</br>

--- 
### 과제 제출
기존 제출 :   1431, 14425, 19636, 1946, 9375
추가 제출 :   

</br>

2023-02-20 14:24 UTC, suhhyun524 commented
출력 관련해서 궁금한 점이 있습니다.
여러개의 테스트케이스를 입력받고 그에 따른 결과를 출력하는 문제에서
첫번째 테스트케이스 결과가 출력되고 두번째 테스트케이스에 관한 결과가 바로 출력되는 것이 아닌, 엔터를 입력해야만 결과가 나옵니다.

예를 들자면, 

#백준 9375번
<img width="305" alt="스크린샷 2023-02-20 오후 11 20 11" src="https://user-images.githubusercontent.com/97878992/220132001-33d62f85-23dd-460b-8e72-33d82e765445.png">
위와 같은 경우에서 엔터를 입력해야만
<img width="305" alt="스크린샷 2023-02-20 오후 11 21 16" src="https://user-images.githubusercontent.com/97878992/220132263-c944f56c-a9bf-41f1-bc25-bc4c747b0450.png">
이렇게 두번째 테스트케이스의 결과가 나오게 됩니다..
절 혼란스럽게 만드는 것은, 저렇게 코드가 나와도 백준은 맞다고 채점을 해준다는 것입니다.....ㅠㅠㅠ

과제 제출은 결과값을 담는 배열을 하나 만들어서 for loop으로 반복 출력하는 것으로 해결하였는데, 별로 마음에 드는 방법이 아니라서 혹시나 이유를 아시나 하고 질문 드립니다

혹시 도전문제라서 답변이 어려우시다면 그냥 무시해주세요!🥹🥹

2023-02-20 16:25 UTC, jk0527 reviewed
9375번 출력 관련하여 테스트케이스마다 엔터를 눌러야 하는 코드 올려주실 수 있을까요? 백준에서 '맞았습니다'가 나오면 잘 푸신 거예요. 굳이 arr배열 만들어서 결과 저장하실 필요 없습니다! 그냥 컴파일러 차이일 수도 있어요. 컴파일러 어떤 거 사용하시나요??

2023-02-20 16:30 UTC, suhhyun524 commented
코드는 지금 브랜치에 올라와있어요!!
mac에서 clion 이용하고 있는데 온라인gdb와 윈도우 clion에서도 모두 같은 현상이 발생했습니다ㅠ.ㅠ

2023-02-20 16:33 UTC, dooli1971039 commented
엔터를 누르는 이유는 저 빨간색 동그라미 부분에는 엔터 or 공백이 없기 때문입니다!
cin으로 입력을 받으니, 공백이나 엔터를 만나면 거기서 짤라서 입력을 받잖아요?
현재 예시에서 가장 마지막의 face는 엔터를 쳐줘야 face 단어를 cin이 인식을 해서 입력이 되는겁니다. 그 전에 makeup 단어까지는 모두 입력이 다 들어간거에요.
즉, 엔터를 누르지 않은 상태는 그 이전 테스트케이스들은 모두 입력이 다 들어가서 바로 출력이 되지만, 마지막 테스트케이스는 다 name은 입력받고 type은 아직 입력받지 못했기 때문에 바로 결과 출력이 안되는 겁니다.
![image](https://user-images.githubusercontent.com/70802352/220159397-ddccdd89-3da0-479e-aa34-6a4027f54ce0.png)

2023-02-20 16:34 UTC, jk0527 reviewed
근데 제출하신 9375.cpp 코드에 에러 있어서 안 돌아가요!

2023-02-20 16:34 UTC, jk0527 commented on 01_정렬, 맵, 셋/도전/9375.cpp
> +    int arr[n];
배열(array)은 이렇게 초기화하실 수 없어요. 배열을 입력값으로 초기화하려면 동적할당하셔야 해요!

2023-02-20 16:39 UTC, dooli1971039 commented on 01_정렬, 맵, 셋/도전/9375.cpp
> +    int arr[n];
저는 잘 돌아가긴 합니다! 아마 차이가 발생하는 이유는 https://blog.naver.com/PostView.nhn?blogId=hirit808&logNo=221447722807&parentCategoryNo=&categoryNo=26&viewDate=&isShowPopularPosts=false&from=postView 이래서인 것 같아요.
c++ 에서 원칙적으로는 배열을 저렇게 동적으로 초기화할 수 없는게 맞습니다! (c언어처럼요!)

2023-02-20 16:52 UTC, jk0527 commented on 01_정렬, 맵, 셋/도전/9375.cpp
> +    int arr[n];
오 그렇군요! 이런 기능이 있네요..! 감사합니다😊

2023-02-20 16:53 UTC, suhhyun524 commented on 01_정렬, 맵, 셋/도전/9375.cpp
> +    int arr[n];
감사합니다! 동적할당으로 수정해서 코드 올렸습니다ㅎㅎ

2023-02-20 16:55 UTC, jk0527 reviewed
지금 올려주신 코드는 arr 배열에 한 번 저장했다가 출력을 하는데 아마 질문 주신 코드는 아래처럼 테스트케이스마다 출력하는 코드일 것 같아요..! 이렇게 짜면 엔터를 마지막에 한 번만 치면 잘 도는데 혹시 이걸 질문하신 게 맞을까요?

```
#include <iostream>
#include <map>

using namespace std;

int calc(map<string, int> clothes) {
    map<string, int>::iterator it;

    int sum = 1;

    for (it = clothes.begin(); it != clothes.end(); it++) {
        sum *= (it->second + 1);
    }
    return sum - 1;
}

int main() {
    int n;
    cin >> n;
    int arr[n];

    for (int i = 0; i < n; i++) {
        int m;
        cin >> m;
        map<string, int> clothes;
        // 입력 및 연산
        while (m--) {
            string name, type;
            cin >> name >> type;
            if (clothes.find(type) != clothes.end()) {
                clothes[type]++;
            } else {
                clothes[type] = 1;
            }
        }
        // 출력
        cout << calc(clothes) << '\n';
    }
}
```

2023-02-20 16:56 UTC, suhhyun524 commented
헉 궁금증 해결했습니다 감사합니당🥹🥹

2023-02-22 16:27 UTC, jk0527 requested changes
**[정렬, 맵, 셋 알고리즘 코드 리뷰 완료]**

1946(P2), 9375(P3), 1431(P1), 14425(P3)

수현님 안녕하세요!
첫 과제인데도 정말 깔끔하게 풀어주셨네요!🥰🥰
도전 문제까지 모두 풀어서 제출하신 것 너무 좋아요!!
코드에 대한 간단한 주석이 있으면 금상첨화일 것 같아요.😎
몇 가지 사소한 코멘트 드렸습니다.
궁금한 점이 있으면 리뷰어를 호출해주세요!

2023-02-22 16:27 UTC, jk0527 commented on 01_정렬, 맵, 셋/도전/1946.cpp
> +    int count = 1;
함수 이름도, 변수 이름도 count이네요..! 이름은 겹치지 않는 것이 좋을 것 같아요. 이건 꼭 수정해주시면 좋을 것 같아요!! (그리고 count는 내장 함수 이름으로 많이 사용되는 단어라 변수명이나 함수명으로는 사용하지 않는 것이 좋아요! )

2023-02-22 16:27 UTC, jk0527 commented on 01_정렬, 맵, 셋/도전/1946.cpp
> +    int arr[n];
vector를 사용하는 것은 어떨까요? 앞으로는 vector를 사용할 일이 정말 많아요!

2023-02-22 16:27 UTC, jk0527 commented on 01_정렬, 맵, 셋/도전/1946.cpp
> +        arr[i] = count(m, apy);
map에 데이터가 오름차순으로 정렬되어있다는 성질을 사용하셨네요. 생각해보지 못한 풀이네요!😎

2023-02-22 16:27 UTC, jk0527 commented on 01_정렬, 맵, 셋/도전/1946.cpp
> +    }
굳이 arr에 저장하지 말고 test case마다 출력하셔도 됩니다.

2023-02-22 16:27 UTC, jk0527 commented on 01_정렬, 맵, 셋/도전/1946.cpp
> +    for (int i = 0; i < n; i++) {
n은 다시 사용하지 않으니 while 문으로 구현해도 될 것 같아요!

2023-02-22 16:27 UTC, jk0527 commented on 01_정렬, 맵, 셋/도전/9375.cpp
> +}
함수화하신 것 정말 좋네요!!

2023-02-22 16:27 UTC, jk0527 commented on 01_정렬, 맵, 셋/도전/9375.cpp
> +            }
하나로 합칠 수 있을 것 같아요. 처음에 꼭 1로 초기화해야 할까요? (이론 수업시간 마지막에 다루었던 'no_key' 문제에 대해 생각해보세요!)

2023-02-22 16:27 UTC, jk0527 commented on 01_정렬, 맵, 셋/도전/9375.cpp
> +        arr[i] = calc(clothes);
마찬가지로 test case마다 출력하셔도 됩니다!

2023-02-22 16:27 UTC, jk0527 commented on 01_정렬, 맵, 셋/필수/1431.cpp
> +bool comp(string s1, string s2) {
reference로 넘겨주면 좋을 것 같아요! `bool comp(string& s1, string& s2)`

2023-02-22 16:27 UTC, jk0527 commented on 01_정렬, 맵, 셋/필수/1431.cpp
> +            }
똑같은 연산을 반복하고 있네요..! 함수화해도 좋을 것 같아요!

2023-02-22 16:27 UTC, jk0527 commented on 01_정렬, 맵, 셋/필수/1431.cpp
> +    if (s1.length() < s2.length()) {
클 때, 같을 때, 작을 때 세 가지로 구분하셨네요. 다를 때와 같을 때로 구분해서 풀 수도 있을 것 같아요. 그리고 리턴할 때 true, false를 직접 넘기지 말고 조건을 넣어주면 더 간단하게 풀 수 있습니다!

2023-02-22 16:27 UTC, jk0527 commented on 01_정렬, 맵, 셋/필수/1431.cpp
> +                }
for문 없이 사전순으로 더 간단하게 비교할 수 있어요!

2023-02-22 16:27 UTC, jk0527 commented on 01_정렬, 맵, 셋/필수/1431.cpp
> +    // 왜 while(n--)로 입력받으면 제대로 작동하지 않는걸까요?
출력할 때 n을 다시 사용하기 때문에 n 값을 바꾸면 안 돼요!

2023-02-22 16:27 UTC, jk0527 commented on 01_정렬, 맵, 셋/필수/14425.cpp
> +    }
코드 깔끔하고 좋아요! 😎😎

2023-02-23 16:24 UTC, grdnr13 approved these changes
**[정렬, 맵, 셋 구현 코드 리뷰 완료]**
19636(P3)
수현님 안녕하세요!
첫 과제인데도 너무 깔끔하게 잘 풀어주셨네요! 🥰🥰
코드 주석이 조금 더 있으면 더 좋을 것 같아요
몇 가지 간단한 코멘트 드렸으니, 확인해주시고 궁금한 점이 있으면 리뷰어를 호출해주세요!

구현 문제는 이대로 머지하셔도 될 것 같아요! 수고하셨습니다

2023-02-23 16:24 UTC, grdnr13 commented on 01_정렬, 맵, 셋/필수/19636.cpp
> +        next_weight += next_delta;
일일 기초 대사량 변화를 고려하지 않는 경우는 반복문을 돌리지 않고도 바로 연산으로도 구할 수 있어요~

2023-02-23 16:24 UTC, grdnr13 commented on 01_정렬, 맵, 셋/필수/19636.cpp
> +void calc(int weight, int basic_meta, int threshold, int day, int energy_in, int energy_out) {
아예 솔루션 함수를 따로 작성해주셨네요! 프로그래머스 같은 사이트에서는 솔루션 함수만을 작성하라고 요구하니, 좋은 습관 같아요😃

2023-02-23 16:24 UTC, grdnr13 commented on 01_정렬, 맵, 셋/필수/19636.cpp
> +        }
코드 깔끔하게 잘 구현해주셨네요😎😎

2023-02-25 04:35 UTC, jk0527 reviewed
**[정렬, 맵, 셋 코드 수정 확인 완료]**
1946(P3), 1431(P3)

수정해주신 부분 모두 확인했습니다~! 😎 
모두 좋습니다! 고생하셨습니다!! 🥰🥰

2023-02-25 04:35 UTC, jk0527 approved these changes

2023-02-28 13:00 UTC, merged