[정수론] 2176279 이유진
Altu-Bitu-Official/Altu-Bitu-4 pull request #96
Opened 2023-03-07 06:33 UTC by YJin33

### 인적사항
학번:    2176279
이름:    이유진
</br>

--- 
### 과제 제출
기존 제출 :   1735,6588
추가 제출 :   

</br>

2023-03-09 10:02 UTC, dooli1971039 approved these changes
**[정수론 추가제출 확인]**
유진님 안녕하세요!
추가제출 확인했습니다~

+) 과제 하실때 브랜치를 어디서 파시나요? 공식레포에 튜터들이 남긴 커밋이 전부 반영이 되네요. 새로운 과제를 할 때, 개인 레포의 main 브랜치를 기준으로 과제 브랜치를 파주세요😄

2023-03-09 11:49 UTC, kwakrhkr59 requested changes
**[정수론 알고리즘 코드 리뷰 완료]**
- 6588: P1

안녕하세요 유진님~ 정수론 필수 알고리즘 문제 코드 리뷰 완료되셨습니다😊 유클리드 호제법과 에라토스테네스의 체를 활용해 문제를 정말 잘 풀어주셨더라고요👍👍 코드도 갈끔하고 다 너무 좋았는데 딱 한 부분 수정이 필요해 보이는 부분이 있어 코멘트 남겨드렸습니다! 수정해주시고 리뷰어로 호출해주시면 머지해드리도록 하겠습니다😁

2023-03-09 11:49 UTC, kwakrhkr59 commented on 03_정수론/필수/1735.cpp
> +    final_denominator = mutiple_of_denominators / greatest_common_divisor;
최대공약수를 활용해서 기약분수를 잘 계산해주고 계시네요! 아주 좋습니다👍👍

2023-03-09 11:49 UTC, kwakrhkr59 commented on 03_정수론/필수/6588.cpp
> +    vector<int> is_prime(MAX + 1, 1); // 소수 여부 저장
상수를 사용해 소수 범위를 잘 설정해주셨네요😍 대신 is_prime에는 소수인지 아닌지를 저장하기 위한 0과 1 값만 사용되니 bool 타입을 써준다면 메모리를 훨씬 더 효율적으로 사용할 수 있을 것 같아요!

2023-03-09 11:49 UTC, kwakrhkr59 commented on 03_정수론/필수/6588.cpp
> +        }
예외 사항을 잘 체크해주셨네요!👍👍 백준에서는 주어진 입력 범위가 아닌 케이스는 테스트되지 않으니 맘 편하게 믿고(?) 푸셔도 괜찮지만 이렇게 혹시 모를 예외를 처리해주는 것도 좋은 습관인 것 같습니다😁

2023-03-09 11:49 UTC, kwakrhkr59 commented on 03_정수론/필수/6588.cpp
> +        if (a == 0)
P1. 정말 다 좋은데 `if (a == 0)`만 한 번 다시 체크해주세요! 지금 들어가고 있는 a는 무슨 값일까요? while문 전에 `a = 0`이라고 선언해주셨기 때문에 a 자체에는 값이 들어가있지만, 테스트 케이스가 여러 개 들어갈 경우 문제가 될 수 있어요😥 사실 골드바흐의 추측 문제은 반례가 증명되지 않아서 해당 if문을 통과하는 경우는 없지만, 만약 위 for문을 돌지 않는 경우를 생각해본다면 그 때의 a는 이전에 계산된 a값을 가지고 거예요! 이번 문제는 특수한 경우기 때문에 괜찮았지만, 만약 반례가 존재한다면 오류의 가능성을 가지고 있기 때문에 수정해주시면 좋을 것 같습니다😊

2023-03-09 12:25 UTC, YJin33 commented on 03_정수론/필수/6588.cpp
> +        if (a == 0)
네 a를 while문 안쪽에서 정의해주는 것으로 수정했습니다!

2023-03-14 02:40 UTC, kwakrhkr59 approved these changes

2023-03-14 02:40 UTC, merged