[정수론] 2029037 정지혜
Altu-Bitu-Official/Altu-Bitu-4 pull request #97
Opened 2023-03-07 06:35 UTC by dahlia52

### 인적사항
학번:   2029037
이름:   정지혜
</br>

--- 
### 과제 제출
기존 제출 :   2840, 6588, 1735, 9421
추가 제출 :   

</br>

2023-03-07 06:36 UTC, dahlia52 commented
2840 예시의 입출력은 맞다고 뜨는데 백준에 코드 입력해보면 틀렸다고 뜹니다..

6588은 자꾸 시간초과가 뜹니다. 구글링의 다른 코드와 비교했을 때, 크게 다른 점이 없어보이던데.. 어떤 점을 개선하면 좋을까요?

2023-03-09 10:08 UTC, dooli1971039 requested changes
[정수론 구현 코드 리뷰 완료]
2840(P1)
지혜님 안녕하세요!

중간에 조건 체크하는 부분의 수정이 필요해 보입니다! 현재 알파벳 중복 체크가 안 되고 있어요.
확인해보시고 수정 후 다시 리뷰어를 호출해주세요~

+) 지금 보니까 과제 제출을 하는 브랜치가 main이네요! 새로운 과제를 할 때, 개인 레포의 main 브랜치를 기준으로 과제 브랜치를 파주세요😄

2023-03-09 10:08 UTC, dooli1971039 commented on 03_정수론/필수/2840.cpp
> +        }
p1. 값이 들어가 있지 않지만, 넣으려는 값이 이미 원판의 다른 부분에 사용이 되었으면 원판을 만들 수 없습니다! 이 부분에 대한 조건 처리가 필요해보입니다. (지금 알파벳 중복 관리하는 코드가 없어요)

2023-03-09 12:16 UTC, kwakrhkr59 approved these changes
**[정수론 알고리즘 코드 리뷰 완료]**
- 6588: P3

안녕하세요 지혜님~ 정수론 필수 알고리즘 문제 코드 리뷰 완료되셨습니다😊 유클리드 호제법과 에라토스테네스의 체를 활용해서 문제를 깔끔하게 잘 풀어주셨네요!👍👍 로직이 깔끔해서 특별히 드릴 말슴은 없었고, 코드 컨벤션 관련해서 몇 가지 리뷰 남겨드렸습니다! 확인해주시고 질문 있으시면 언제든 리뷰어로 호출해주세요😊 수고 많으셨습니다~

2023-03-09 12:16 UTC, kwakrhkr59 commented on 03_정수론/필수/1735.cpp
> +    }
최대공약수를 사용해 기약분수를 잘 계산해주고 계시네요! f가 1이 되더라도 l과 u는 그 값을 유지할테니 if문은 사용하지 않으셔도 원하시던 대로 코드를 구현할 수 있을 것 같습니다😁

2023-03-09 12:16 UTC, kwakrhkr59 commented on 03_정수론/필수/6588.cpp
> +void sosu(vector<bool> &s, int n){
&를 사용해 바로 값을 계산해주셨네요! 아주 좋습니다👍👍

2023-03-09 12:16 UTC, kwakrhkr59 commented on 03_정수론/필수/6588.cpp
> +                    s[j] = false;
P3. 지금 중첩이 4겹이네요! 중첩이 많아지면 많아질수록 이 코드가 어떤 for문에 속한 건지 어떤 if문에 속한 건지 알아보기가 어려워지죠😥 인덴테이션은 최대한 3겹을 넘지 않도록 작성해주시고, 중첩을 줄이고 싶으실 대는 continue나 return을 적극적으로 사용해주세요!

2023-03-09 12:16 UTC, kwakrhkr59 commented on 03_정수론/필수/6588.cpp
> +            break;
P3. if문이나 for문은 안에 들어가는 코드가 한 줄 짜리이면 중괄호를 작성하지 않아도 되지만, 협업이나 수정이 필요할 경우 꽤 귀찮은 작업으로 이어질 수 있어요! if문에 딱 한 줄짜리 코드가 들어가더라도 중괄호는 반드시 작성해주시면 좋을 것 같습니다😊

2023-03-09 12:27 UTC, kwakrhkr59 requested changes

2023-03-09 12:27 UTC, kwakrhkr59 commented on 03_정수론/필수/6588.cpp
> +    vector<bool> s(n+1, true);
P1. 입력값의 범위를 다시 한 번 확인해주세요! 실제 테스트 케이스의 범위를 확인하시면 시간 초과의 이유를 파악할 수 있으실 것 같네요😁

2023-06-25 08:18 UTC, closed without merging